# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Kinther's Blog
site_url: https://kinthero.github.io/blog
site_author: kinther
site_description: >-
  kinther's blog

# Repository
repo_name: kinthero/blog
repo_url: https://github.com/kinthero/blog

# Copyright
copyright: Copyright &copy; 2025 kinther


theme:
  name: material
  custom_dir: overrides
  language: zh
  icon:
    logo: simple/known
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # 页脚显示上下一页
    - navigation.footer
    # 节下面的 index 文件可以作为该节概述
    - navigation.indexes
    # 最顶层目录作为顶部的 tab
    - navigation.tabs
    # 固定 tab
    # - navigation.tabs.sticky
    # 性能优化
    - navigation.prune
    # 回到顶部功能
    - navigation.top
    # 浏览的时候，地址 URL 会更新锚点
    - navigation.tracking
    # 阅读的时候右侧锚点会跟随
    - toc.follow
    - search.highlight
    - search.share
    - search.suggest
  palette: 
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: teal
      accent: red
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: white
      accent: red
  font:
    text: LXGW WenKai TC
    code: Fira Code
  
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: kinther
      repo: site
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      # slugify: !!python/object/apply:pymdownx.slugs.slugify
      # kwds:
      # case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

extra:
  social:
    - icon: simple/github
      link: https://kinthero.github.com
    - icon: simple/rss
      link: https://kinthero.github.io/blog/feed_rss_created.xml

plugins:
  - search
  - blog:
      blog_dir: .
      authors: true
      blog_toc: true
      pagination_per_page: 10
      post_url_format: "{slug}"
      categories_allowed:
        - python
        - llm
        - math
        - misc
        - how-to
        - idea
  - meta
  - tags
  - rss:
      match_path: "posts/.*"
      pretty_print: true
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
